from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(Cart)
admin.site.register(Category)
admin.site.register(Coupon)
admin.site.register(FeaturedProduct)
admin.site.register(Keywords)
admin.site.register(Order)
admin.site.register(Photo)
admin.site.register(Point)
admin.site.register(ProductInTransaction)
admin.site.register(Product)
admin.site.register(Slider)
admin.site.register(SiteConfig)
admin.site.register(Wishlist)
admin.site.register(Tag)
admin.site.register(Rating)
admin.site.register(Status)
admin.site.register(Tracker)
admin.site.register(Inquiry)
admin.site.register(Sales)
admin.site.register(NotifyMe)
admin.site.register(RecentlyViewed)
admin.site.register(Advertisement)
admin.site.register(ProductRefund)
admin.site.register(Tracking)
admin.site.register(OrderTracking)
# admin.site.register(Ship)
admin.site.register(Sender)
admin.site.register(Story)
admin.site.register(File)
admin.site.register(SubCategory)
